from enums import Type

fulcrums_type_data = {
    Type.NORMAL: [
        (Type.FLYING, Type.FLYING),
        (Type.PSYCHIC, Type.PSYCHIC),
        (Type.FAIRY, Type.FAIRY),
        (Type.FLYING, Type.PSYCHIC),
        (Type.FLYING, Type.FAIRY),
        (Type.FAIRY, Type.PSYCHIC),
    ],
    Type.FIRE: [
        (Type.GRASS, Type.GRASS),
        (Type.WATER, Type.ELECTRIC),
        (Type.WATER, Type.GRASS),
    ],
    Type.WATER: [
        (Type.FIRE, Type.GROUND),
        (Type.ICE, Type.GROUND),
        (Type.POISON, Type.GROUND),
        (Type.FLYING, Type.GROUND),
        (Type.BUG, Type.GROUND),
        (Type.FIRE, Type.FIRE),
        (Type.BUG, Type.BUG),
        (Type.BUG, Type.POISON),
    ],
    Type.GRASS: [
        (Type.ROCK, Type.GROUND),
        (Type.ROCK, Type.PSYCHIC),
        (Type.GROUND, Type.FIRE),
        (Type.ROCK, Type.ROCK),
        (Type.GROUND, Type.STEEL),
        (Type.GROUND, Type.ELECTRIC),
        (Type.GROUND, Type.FLYING),
        (Type.GROUND, Type.ICE),
        (Type.ROCK, Type.STEEL),
        (Type.GROUND, Type.GROUND),
    ],
    Type.ELECTRIC: [
        (Type.WATER, Type.WATER),
        (Type.GRASS, Type.GRASS),
        (Type.ICE, Type.ICE),
        (Type.WATER, Type.GRASS),
        (Type.WATER, Type.ICE),
        (Type.ICE, Type.GRASS),
    ],
    Type.ICE: [
        (Type.GROUND, Type.FLYING),
        (Type.GROUND, Type.PSYCHIC),
        (Type.GROUND, Type.FAIRY),
        (Type.WATER, Type.GROUND),
        (Type.FLYING, Type.WATER),
    ],
    Type.FIGHTING: [
        (Type.POISON, Type.BUG),
        (Type.POISON, Type.GHOST),
        (Type.STEEL, Type.ELECTRIC),
        (Type.STEEL, Type.ROCK),
    ],
    Type.POISON: [
        (Type.WATER, Type.BUG),
        (Type.WATER, Type.GHOST),
        (Type.WATER, Type.DARK),
        (Type.GRASS, Type.BUG),
        (Type.GRASS, Type.GHOST),
        (Type.GRASS, Type.DARK),
        (Type.ICE, Type.BUG),
        (Type.ICE, Type.GHOST),
        (Type.ICE, Type.DARK),
    ],
    Type.GROUND: [
        (Type.FIRE, Type.GRASS),
        (Type.FIRE, Type.ELECTRIC),
        (Type.BUG, Type.GRASS),
        (Type.BUG, Type.STEEL),
        (Type.ELECTRIC, Type.FLYING),
        (Type.BUG, Type.ELECTRIC),
        (Type.ICE, Type.ELECTRIC),
        (Type.BUG, Type.ROCK),
        (Type.BUG, Type.STEEL),
        (Type.FLYING, Type.FIGHTING),
        (Type.BUG, Type.FIGHTING),
        (Type.ROCK, Type.FLYING),
    ],
    Type.FLYING: [
        (Type.GROUND, Type.FIRE),
        (Type.GROUND, Type.FIGHTING),
        (Type.GROUND, Type.ROCK),
        (Type.GROUND, Type.STEEL),
        (Type.FIGHTING, Type.FIGHTING),
        (Type.STEEL, Type.STEEL),
        (Type.ROCK, Type.FIGHTING),
    ],
    Type.PSYCHIC: [
        (Type.FAIRY, Type.GHOST),
        (Type.FIGHTING, Type.DARK),
        (Type.FAIRY, Type.DARK),
        (Type.BUG, Type.GHOST),
        (Type.FIGHTING, Type.GHOST),
        (Type.BUG, Type.DARK),
        (Type.FAIRY, Type.FAIRY),
        (Type.DARK, Type.DARK),
        (Type.FIRE, Type.DARK),
        (Type.FAIRY, Type.FAIRY),
        (Type.BUG, Type.FIGHTING),
        (Type.GHOST, Type.FLYING),
    ],
    Type.BUG: [
        (Type.WATER, Type.ELECTRIC),
        (Type.WATER, Type.ROCK),
        (Type.ROCK, Type.GROUND),
        (Type.GROUND, Type.ELECTRIC),
    ],
    Type.ROCK: [
        (Type.FIRE, Type.FIGHTING),
        (Type.FIRE, Type.FLYING),
        (Type.FIGHTING, Type.FLYING),
        (Type.ICE, Type.FIGHTING),
        (Type.FIRE, Type.PSYCHIC),
        (Type.FIRE, Type.FAIRY),
        (Type.GRASS, Type.FIRE),
        (Type.GRASS, Type.FLYING),
        (Type.FLYING, Type.WATER),
        (Type.FLYING, Type.ICE),
        (Type.FLYING, Type.GROUND),
        (Type.FLYING, Type.FIGHTING),
        (Type.FLYING, Type.ELECTRIC),
    ],
    Type.GHOST: [
        (Type.FAIRY, Type.GHOST),
        (Type.FAIRY, Type.DARK),
        (Type.FIGHTING, Type.GHOST),
        (Type.FIGHTING, Type.DARK),
        (Type.BUG, Type.GHOST),
        (Type.BUG, Type.DARK),
        (Type.DARK, Type.DARK),
        (Type.DARK, Type.FIRE),
        (Type.FAIRY, Type.FAIRY),
        (Type.FAIRY, Type.FAIRY),
    ],
    Type.DRAGON: [
        (Type.STEEL, Type.STEEL),
        (Type.STEEL, Type.ICE),
        (Type.STEEL, Type.DRAGON),
        (Type.STEEL, Type.FAIRY),
        (Type.STEEL, Type.PSYCHIC),
        (Type.STEEL, Type.BUG),
        (Type.FIGHTING, Type.POISON),
        (Type.POISON, Type.FIRE),
        (Type.ICE, Type.FIGHTING),
        (Type.DRAGON, Type.FIGHTING),
        (Type.FAIRY, Type.ROCK),
        (Type.FAIRY, Type.STEEL),
        (Type.FAIRY, Type.FIGHTING),
    ],
    Type.DARK: [
        (Type.FLYING, Type.POISON),
        (Type.FLYING, Type.STEEL),
        (Type.FLYING, Type.FLYING),
        (Type.FLYING, Type.FLYING),
        (Type.FIRE, Type.POISON),
        (Type.FIRE, Type.STEEL),
        (Type.FLYING, Type.ELECTRIC),
        (Type.FLYING, Type.WATER),
    ],
    Type.STEEL: [
        (Type.WATER, Type.FLYING),
        (Type.WATER, Type.PSYCHIC),
        (Type.WATER, Type.FAIRY),
        (Type.WATER, Type.WATER),
    ],
    Type.FAIRY: [
        (Type.GROUND, Type.GROUND),
        (Type.GROUND, Type.PSYCHIC),
        (Type.GROUND, Type.FIRE),
        (Type.GROUND, Type.FIGHTING),
        (Type.PSYCHIC, Type.FIRE),
    ],
}

pivots_type_data = {
    Type.NORMAL: [
        (Type.GHOST, Type.GHOST),
        (Type.GHOST, Type.GHOST),
        (Type.GHOST, Type.BUG),
        (Type.GHOST, Type.STEEL),
        (Type.GHOST, Type.FAIRY),
        (Type.GHOST, Type.DARK),
        (Type.GHOST, Type.PSYCHIC),
        (Type.GHOST, Type.WATER),
        (Type.GHOST, Type.ELECTRIC),
        (Type.GHOST, Type.GRASS),
        (Type.GHOST, Type.FIRE),
        (Type.GHOST, Type.ICE),
        (Type.GHOST, Type.FIGHTING),
        (Type.GHOST, Type.POISON),
        (Type.GHOST, Type.GROUND),
        (Type.GHOST, Type.ROCK),
        (Type.GHOST, Type.FLYING),
        (Type.GHOST, Type.DRAGON),
    ],
    Type.FIRE: [
        (Type.GRASS, Type.FIGHTING),
        (Type.GRASS, Type.GRASS),
        (Type.GRASS, Type.POISON),
        (Type.GRASS, Type.GRASS),
        (Type.GRASS, Type.GHOST),
        (Type.GRASS, Type.WATER),
        (Type.GRASS, Type.PSYCHIC),
        (Type.GRASS, Type.DRAGON),
        (Type.GRASS, Type.DARK),
        (Type.GRASS, Type.FAIRY),
    ],
    Type.WATER: [
        (Type.GRASS, Type.POISON),
        (Type.GRASS, Type.PSYCHIC),
        (Type.GRASS, Type.STEEL),
        (Type.GRASS, Type.DRAGON),
        (Type.DRAGON, Type.POISON),
        (Type.DRAGON, Type.DRAGON),
        (Type.DRAGON, Type.ELECTRIC),
        (Type.STEEL, Type.ELECTRIC),
        (Type.DRAGON, Type.DARK),
        (Type.ELECTRIC, Type.GROUND),
    ],
    Type.GRASS: [
        (Type.FIRE, Type.ROCK),
        (Type.WATER, Type.ROCK),
        (Type.FIRE, Type.ELECTRIC),
        (Type.FLYING, Type.ROCK),
        (Type.POISON, Type.ROCK),
        (Type.POISON, Type.WATER),
        (Type.WATER, Type.GHOST),
        (Type.FIRE, Type.GHOST),
    ],
    Type.ELECTRIC: [
        (Type.DRAGON, Type.GROUND),
        (Type.GHOST, Type.GHOST),
        (Type.FLYING, Type.GROUND),
    ],
    Type.ICE: [
        (Type.WATER, Type.FIGHTING),
        (Type.WATER, Type.GROUND),
        (Type.WATER, Type.PSYCHIC),
        (Type.STEEL, Type.GHOST),
        (Type.WATER, Type.POISON),
        (Type.WATER, Type.GHOST),
    ],
    Type.FIGHTING: [
        (Type.STEEL, Type.GROUND),
        (Type.STEEL, Type.PSYCHIC),
        (Type.STEEL, Type.STEEL),
        (Type.STEEL, Type.ELECTRIC),
        (Type.STEEL, Type.FLYING),
        (Type.STEEL, Type.FAIRY),
        (Type.STEEL, Type.ROCK),
    ],
    Type.POISON: [
        (Type.WATER, Type.POISON),
        (Type.WATER, Type.GROUND),
        (Type.STEEL, Type.GROUND),
        (Type.GROUND, Type.FIRE),
        (Type.STEEL, Type.FIGHTING),
        (Type.WATER, Type.STEEL),
        (Type.STEEL, Type.DARK),
        (Type.GHOST, Type.FIRE),
        (Type.STEEL, Type.POISON),
        (Type.WATER, Type.GHOST),
    ],
    Type.GROUND: [
        (Type.WATER, Type.FIRE),
        (Type.WATER, Type.FLYING),
        (Type.WATER, Type.STEEL),
        (Type.WATER, Type.POISON),
        (Type.STEEL, Type.GRASS),
        (Type.STEEL, Type.GHOST),
        (Type.STEEL, Type.PSYCHIC),
        (Type.STEEL, Type.ICE),
        (Type.STEEL, Type.DARK),
    ],
    Type.FLYING: [
        (Type.ELECTRIC, Type.STEEL),
        (Type.GROUND, Type.WATER),
        (Type.GROUND, Type.STEEL),
        (Type.GROUND, Type.ICE),
        (Type.STEEL, Type.STEEL),
        (Type.STEEL, Type.FAIRY),
        (Type.STEEL, Type.ROCK),
        (Type.ELECTRIC, Type.WATER),
    ],
    Type.PSYCHIC: [
        (Type.FIRE, Type.FIGHTING),
        (Type.FIGHTING, Type.POISON),
        (Type.FAIRY, Type.FLYING),
        (Type.FLYING, Type.FIGHTING),
        (Type.FAIRY, Type.STEEL),
        (Type.FAIRY, Type.BUG),
        (Type.BUG, Type.FIGHTING),
        (Type.FIGHTING, Type.STEEL),
        (Type.DARK, Type.FIRE),
        (Type.DARK, Type.GROUND),
        (Type.DARK, Type.FLYING),
        (Type.FIGHTING, Type.FIGHTING),
        (Type.FIGHTING, Type.GROUND),
        (Type.FIGHTING, Type.ROCK),
        (Type.FIGHTING, Type.WATER),
        (Type.FIGHTING, Type.ELECTRIC),
        (Type.FIGHTING, Type.ICE),
        (Type.FIGHTING, Type.FAIRY),
    ],
    Type.BUG: [
        (Type.GROUND, Type.ROCK),
        (Type.ROCK, Type.ELECTRIC),
        (Type.ROCK, Type.ROCK),
        (Type.ROCK, Type.DARK),
        (Type.ROCK, Type.STEEL),
        (Type.ROCK, Type.FAIRY),
        (Type.ROCK, Type.PSYCHIC),
        (Type.STEEL, Type.WATER),
        (Type.STEEL, Type.FIRE),
    ],
    Type.ROCK: [
        (Type.STEEL, Type.FLYING),
        (Type.DRAGON, Type.FLYING),
        (Type.FLYING, Type.POISON),
        (Type.BUG, Type.FLYING),
    ],
    Type.GHOST: [
        (Type.DARK, Type.DARK),
        (Type.DARK, Type.DARK),
        (Type.FAIRY, Type.FAIRY),
        (Type.DARK, Type.ROCK),
        (Type.DARK, Type.STEEL),
        (Type.DARK, Type.FAIRY),
        (Type.DARK, Type.WATER),
        (Type.DARK, Type.FIRE),
        (Type.DARK, Type.GROUND),
        (Type.DARK, Type.ICE),
        (Type.DARK, Type.GRASS),
        (Type.FIGHTING, Type.FIGHTING),
        (Type.DARK, Type.DRAGON),
        (Type.FAIRY, Type.FAIRY),
    ],
    Type.DRAGON: [
        (Type.STEEL, Type.STEEL),
        (Type.STEEL, Type.ICE),
        (Type.STEEL, Type.ROCK),
        (Type.STEEL, Type.PSYCHIC),
        (Type.STEEL, Type.FAIRY),
        (Type.STEEL, Type.BUG),
        (Type.STEEL, Type.GROUND),
        (Type.STEEL, Type.GHOST),
        (Type.STEEL, Type.ELECTRIC),
        (Type.STEEL, Type.POISON),
    ],
    Type.DARK: [
        (Type.FIRE, Type.FLYING),
        (Type.POISON, Type.BUG),
        (Type.POISON, Type.POISON),
        (Type.POISON, Type.WATER),
        (Type.POISON, Type.FLYING),
        (Type.POISON, Type.GROUND),
        (Type.FIRE, Type.GHOST),
        (Type.POISON, Type.FIRE),
        (Type.GHOST, Type.STEEL),
        (Type.POISON, Type.ELECTRIC),
        (Type.POISON, Type.FAIRY),
    ],
    Type.STEEL: [
        (Type.FIRE, Type.FLYING),
        (Type.WATER, Type.FLYING),
        (Type.DRAGON, Type.FLYING),
        (Type.FLYING, Type.ELECTRIC),
        (Type.FLYING, Type.POISON),
        (Type.FLYING, Type.GROUND),
        (Type.FLYING, Type.FLYING),
        (Type.FLYING, Type.PSYCHIC),
        (Type.FLYING, Type.FAIRY),
        (Type.FLYING, Type.GHOST),
    ],
    Type.FAIRY: [
        (Type.BUG, Type.GHOST),
        (Type.STEEL, Type.GROUND),
        (Type.STEEL, Type.STEEL),
        (Type.WATER, Type.POISON),
        (Type.STEEL, Type.ELECTRIC),
        (Type.FIRE, Type.GHOST),
        (Type.WATER, Type.GROUND),
        (Type.BUG, Type.STEEL),
        (Type.GROUND, Type.FIRE),
        (Type.STEEL, Type.PSYCHIC),
        (Type.STEEL, Type.WATER),
        (Type.ELECTRIC, Type.GHOST),
        (Type.STEEL, Type.DRAGON),
        (Type.STEEL, Type.DARK),
        (Type.STEEL, Type.GRASS),
        (Type.STEEL, Type.FLYING),
        (Type.STEEL, Type.GHOST),
        (Type.STEEL, Type.POISON),
        (Type.STEEL, Type.FIGHTING),
    ],
}
