#!/usr/bin/env python3
"""
Find all placeholder Pokémon IDs (those with name "-----")
This script identifies Pokémon that are likely alternate forms or placeholders
and generates a blacklist file with their IDs.
"""

import pokemon_shared
import ndspy.rom
import sys

# Check if a ROM file is provided
if len(sys.argv) < 2:
    print("Usage: python find_placeholder_pokemon.py <rom_file>")
    sys.exit(1)

# Load the ROM
rom_path = sys.argv[1]
print(f"Loading ROM file: {rom_path}")
try:
    rom = ndspy.rom.NintendoDSRom.fromFile(rom_path)
except Exception as e:
    print(f"Error loading ROM: {e}")
    sys.exit(1)

# Read Pokémon names
print("Reading Pokémon names...")
try:
    names = pokemon_shared.read_pokemon_names(".")
except Exception as e:
    print(f"Error reading Pokémon names: {e}")
    sys.exit(1)

# Read all Pokémon data
print("Reading Pokémon data...")
try:
    all_pokemon = pokemon_shared.read_mondata(rom, names)
except Exception as e:
    print(f"Error reading Pokémon data: {e}")
    sys.exit(1)

# Find all placeholder Pokémon (with name "-----")
placeholder_ids = []
placeholder_with_info = []

for i, mon in enumerate(all_pokemon):
    if mon.name == "-----":
        placeholder_ids.append(i)
        # Store some info about the Pokémon for analysis
        placeholder_with_info.append((i, mon.bst, mon.type1, mon.type2))

# Print statistics
print(f"\nFound {len(placeholder_ids)} Pokémon with placeholder names ('-----')")
print(f"These represent {len(placeholder_ids) / len(all_pokemon) * 100:.1f}% of all Pokémon in the ROM")

# Print some examples
print("\nFirst 10 placeholder Pokémon examples:")
for i, bst, type1, type2 in placeholder_with_info[:10]:
    print(f"ID: {i:4d}, BST: {bst:4d}, Types: {type1}/{type2}")

# Generate blacklist entries
print("\nGenerating blacklist entries...")
with open("placeholder_pokemon.txt", "w") as f:
    f.write("# Placeholder Pokémon IDs (alternate forms)\n")
    f.write("# These Pokémon have the name '-----' in the ROM and should be excluded from randomization\n")
    f.write("# Generated by find_placeholder_pokemon.py\n\n")
    
    # Write all placeholder IDs to the file
    for pokemon_id in placeholder_ids:
        f.write(f"{pokemon_id}  # Placeholder Pokémon\n")

print(f"\nPlaceholder Pokémon IDs written to placeholder_pokemon.txt")
print("You can copy these IDs to your data/blacklist.txt file to exclude them from randomization")
