#include "../../include/debug.h"
#include "../../include/pokemon.h"
#include "../../include/save.h"
#include "../../include/script.h"
#include "../../include/types.h"
#include "../../include/constants/item.h"

#ifdef MART_EXPANSION

struct MartItem {
    u16 item_id;
    u16 override_cost;
};

struct BadgeMartItems {
    u16 item_id;
    u8 required_badges;
};

// note: limited to 203 items (~34 pages)
const struct BadgeMartItems sBadgeMart[] = {
    { ITEM_POKE_BALL,      0 },
    { ITEM_GREAT_BALL,     3 },
    { ITEM_ULTRA_BALL,     5 },
    { ITEM_POTION,         0 },
    { ITEM_SUPER_POTION,   1 },
    { ITEM_HYPER_POTION,   5 },
    { ITEM_MAX_POTION,     7 },
    { ITEM_FULL_RESTORE,   8 },
    { ITEM_REVIVE,         3 },
    { ITEM_ANTIDOTE,       0 },
    { ITEM_PARALYZE_HEAL,  0 },
    { ITEM_AWAKENING,      1 },
    { ITEM_BURN_HEAL,      1 },
    { ITEM_ICE_HEAL,       1 },
    { ITEM_FULL_HEAL,      5 },
    { ITEM_ESCAPE_ROPE,    1 },
    { ITEM_REPEL,          1 },
    { ITEM_SUPER_REPEL,    3 },
    { ITEM_MAX_REPEL,      5 },
};

void LONG_CALL InitMartUI(void *taskManager, FieldSystem *fieldSystem, const u16 *items, int kind, int buySell, int decoWhich, const struct MartItem *priceOverrides);

u16 sCherrygroveCityMart[] = {
    ITEM_AIR_MAIL, ITEM_HEAL_BALL, 0xFFFF
};

u16 sVioletCityMart[] = {
    ITEM_TUNNEL_MAIL, ITEM_HEAL_BALL, ITEM_NET_BALL, 0xFFFF
};

u16 sAzaleaCityMart[] = {
    ITEM_BLOOM_MAIL, ITEM_HEAL_BALL, ITEM_NET_BALL, 0xFFFF
};

u16 sGoldenrodDepartmentUpper2F[] = {
    ITEM_POTION, ITEM_SUPER_POTION, ITEM_HYPER_POTION, ITEM_MAX_POTION, ITEM_REVIVE,
    ITEM_ANTIDOTE, ITEM_PARALYZE_HEAL, ITEM_BURN_HEAL, ITEM_ICE_HEAL, ITEM_AWAKENING,
    ITEM_FULL_HEAL, 0xFFFF
};

u16 sGoldenrodDepartmentLower2F[] = {
    ITEM_POKE_BALL, ITEM_GREAT_BALL, ITEM_ULTRA_BALL, ITEM_ESCAPE_ROPE, ITEM_POKE_DOLL,
    ITEM_REPEL, ITEM_SUPER_REPEL, ITEM_MAX_REPEL, ITEM_GRASS_MAIL, ITEM_FLAME_MAIL,
    ITEM_BUBBLE_MAIL, ITEM_SPACE_MAIL, 0xFFFF
};

u16 sGoldenrodDepartment3F[] = {
    ITEM_POMEG_BERRY, ITEM_KELPSY_BERRY, ITEM_QUALOT_BERRY, ITEM_HONDEW_BERRY, ITEM_GREPA_BERRY, ITEM_TAMATO_BERRY,
    ITEM_HEALTH_FEATHER, ITEM_MUSCLE_FEATHER, ITEM_RESIST_FEATHER, ITEM_GENIUS_FEATHER, ITEM_CLEVER_FEATHER, ITEM_SWIFT_FEATHER, 0xFFFF
};

u16 sGoldenrodDepartment4F[] = {
    ITEM_PROTEIN, ITEM_IRON, ITEM_CALCIUM, ITEM_ZINC, ITEM_CARBOS,
    ITEM_HP_UP, 0xFFFF
};

u16 sGoldenrodDepartment5F[] = {
    ITEM_TM007, ITEM_TM008, ITEM_TM009, ITEM_TM010, ITEM_TM012, ITEM_TM015, ITEM_TM016, ITEM_TM019, ITEM_TM022
    ITEM_TM028, ITEM_TM029, ITEM_TM030, ITEM_TM031, ITEM_TM032, ITEM_TM033, ITEM_TM036, ITEM_TM040, ITEM_TM044, ITEM_TM045,
    ITEM_TM049, ITEM_TM050, ITEM_TM051, ITEM_TM052, ITEM_TM057, ITEM_TM080, 0xFFFF
};

u16 sGoldenrodHerbs[] = {
    ITEM_HEAL_POWDER, ITEM_ENERGY_POWDER, ITEM_ENERGY_ROOT, ITEM_REVIVAL_HERB, 0xFFFF
};

u16 sEcruteakMart[] = {
    ITEM_FIRE_STONE, ITEM_WATER_STONE, ITEM_THUNDER_STONE, ITEM_LEAF_STONE, ITEM_MOON_STONE, ITEM_SUN_STONE,
    ITEM_MOON_STONE, ITEM_OVAL_STONE, 0xFFFF
};

u16 sOlivineMart[] = {
    ITEM_LAGGING_TAIL, ITEM_BINDING_BAND, ITEM_FLOAT_STONE, ITEM_DESTINY_KNOT, ITEM_GRIP_CLAW, ITEM_STICKY_BARB,
    ITEM_LIGHT_BALL, ITEM_METAL_POWDER, ITEM_THICK_CLUB, ITEM_LEEK, ITEM_QUICK_POWDER 0xFFFF
};

u16 sCianwoodPharmacy[] = {
    ITEM_WHITE_HERB, ITEM_MENTAL_HERB, ITEM_POWER_HERB, ITEM_ABSORB_BULB, ITEM_LUMINOUS_MOSS, ITEM_MIRROR_HERB,
    ITEM_PSYCHIC_SEED, ITEM_MISTY_SEED, ITEM_GRASSY_SEED, ITEM_ELECTRIC_SEED, ITEM_ODD_INCENSE, ITEM_ROCK_INCENSE, ITEM_FULL_INCENSE,
    ITEM_LAX_INCENSE, ITEM_SEA_INCENSE, ITEM_WAVE_INCENSE, ITEM_ROSE_INCENSE, ITEM_LUCK_INCENSE, ITEM_PURE_INCENSE,
    0xFFFF
};

u16 sBlackthornAndBattleFrontierMart[] = {
    ITEM_SHINY_STONE, ITEM_DUSK_STONE, ITEM_DAWN_STONE, ITEM_LINKING_CORDK, ITEM_KINGS_ROCK, ITEM_DEEP_SEA_SCALE, ITEM_DEEP_SEA_TOOTH, ITEM_UP_GRADE,
    ITEM_PRISM_SCALE, ITEM_SACHET, ITEM_WHIPPED_DREAM, ITEM_STRAWBERRY_SWEET, ITEM_CHIPPED_POT, ITEM_CRACKED_POT, ITEM_GALARICA_CUFF,
    ITEM_GALARICA_WREATH, ITEM_SWEET_APPLE, ITEM_TART_APPLE, ITEM_SYRUPY_APPLE, ITEM_UNREMARKABLE_TEACUP, ITEM_MASTERPIECE_TEACUP, 0xFFFF
};

u16 sIndigoPlateau[] = {
    ITEM_TM053, ITEM_TM056, ITEM_TM058, ITEM_TM061, ITEM_TM066, ITEM_TM067, ITEM_TM068, ITEM_TM069, ITEM_TM070, ITEM_TM076,
    ITEM_TM077, ITEM_TM085, ITEM_TM102, ITEM_TM136, ITEM_TM137, ITEM_TM138, ITEM_TM139, ITEM_TM171, ITEM_TM180, ITEM_TM185, ITEM_TM197,
    ITEM_TM199, ITEM_TM200, ITEM_TM209, ITEM_TM215, ITEM_TM228, ITEM_TM226,  0xFFFF
};

u16 sVermilionAndSafariMart[] = {
    ITEM_QUICK_BALL, ITEM_DRAGON_SCALE, ITEM_PROTECTOR, ITEM_ELECTIRIZER, ITEM_MAGMARIZER, ITEM_DUBIOUS_DISC, ITEM_REAPER_CLOTH,
    ITEM_RAZOR_CLAW, ITEM_RAZOR_FANG, ITEM_BLACK_AUGURITE, ITEM_PEAT_BLOCK, ITEM_METAL_ALLOY, ITEM_AUSPICIOUS_ARMOR, ITEM_MALICIOUS_ARMOR,
    ITEM_AMULET_COIN, ITEM_METAL_COAT, 0xFFFF
};

u16 sSaffronMart[] = {
    ITEM_AIR_MAIL, ITEM_DUSK_BALL, ITEM_QUICK_BALL, 0xFFFF
};

u16 sLavenderMart[] = {
    ITEM_AIR_MAIL, ITEM_DUSK_BALL, ITEM_QUICK_BALL, 0xFFFF
};

u16 sCeruleanMart[] = {
    ITEM_AIR_MAIL, ITEM_QUICK_BALL, 0xFFFF
};

u16 sCeladonDepartmentUpper2F[] = {
    ITEM_POTION, ITEM_SUPER_POTION, ITEM_HYPER_POTION, ITEM_MAX_POTION, ITEM_REVIVE,
    ITEM_ANTIDOTE, ITEM_PARALYZE_HEAL, ITEM_BURN_HEAL, ITEM_ICE_HEAL, ITEM_AWAKENING,
    ITEM_FULL_HEAL, 0xFFFF
};

u16 sCeladonDepartmentLower2F[] = {
    ITEM_POKE_BALL, ITEM_GREAT_BALL, ITEM_ULTRA_BALL, ITEM_ESCAPE_ROPE, ITEM_POKE_DOLL,
    ITEM_REPEL, ITEM_SUPER_REPEL, ITEM_MAX_REPEL, ITEM_GRASS_MAIL, ITEM_FLAME_MAIL,
    ITEM_BUBBLE_MAIL, ITEM_SPACE_MAIL, 0xFFFF
};

u16 sCeladonDepartment3F[] = {
    ITEM_TM059, ITEM_TM079, ITEM_TM0106, ITEM_TM112, ITEM_TM115,
    ITEM_TM118, ITEM_TM119, ITEM_TM121, ITEM_TM143, ITEM_TM147,
    ITEM_TM148, ITEM_TM150, ITEM_TM151, ITEM_TM160, ITEM_TM162, ITEM_TM221, 0xFFFF
};

u16 sCeladonDepartment4F[] = {
    ITEM_AIR_MAIL, ITEM_TUNNEL_MAIL, ITEM_BLOOM_MAIL, 0xFFFF
};

u16 sCeladonDepartmentLeft5F[] = {
    ITEM_X_SPEED, ITEM_X_ATTACK, ITEM_X_DEFENSE, ITEM_GUARD_SPEC, ITEM_DIRE_HIT,
    ITEM_X_ACCURACY, ITEM_X_SP_ATK, ITEM_X_SP_DEF, 0xFFFF
};

u16 sCeladonDepartmentRight5F[] = {
    ITEM_PROTEIN, ITEM_IRON, ITEM_CALCIUM, ITEM_ZINC, ITEM_CARBOS,
    ITEM_HP_UP, 0xFFFF
};

u16 sFuschiaMart[] = {
    ITEM_STEEL_MAIL, ITEM_DUSK_BALL, ITEM_QUICK_BALL, 0xFFFF
};

u16 sPewterMart[] = {
    ITEM_ADAMANT_CRYSTAL, ITEM_GRISEOUS_CORE, ITEM_GRISEOUS_ORB, ITEM_LUSTROUS_GLOBE, ITEM_RUSTED_SHIELD,
    ITEM_RUSTED_SWORD, ITEM_SOUL_DEW, ITEM_ADAMANT_ORB, ITEM_LUSTROUS_ORB, 0xFFFF
};

u16 sViridianMart[] = {
    ITEM_STEEL_MAIL, ITEM_NET_BALL, ITEM_HEAL_BALL, 0xFFFF
};

u16 sMtMoonSquare[] = {
    ITEM_GENGARITE, ITEM_GARDEVOIRITE, ITEM_AMPHAROSITE, ITEM_VENUSAURITE, ITEM_CHARIZARDITE_X, ITEM_CHARIZARDITE_Y, ITEM_BLASTOISINITE,
    ITEM_MEWTWONITE_X, ITEM_MEWTWONITE_Y, ITEM_BLAZIKENITE, ITEM_MEDICHAMITE, ITEM_HOUNDOOMINITE, ITEM_AGGRONITE, ITEM_BANETTITE,
    ITEM_TYRANITARITE, ITEM_SCIZORITE, ITEM_PINSIRITE, ITEM_AERODACTYLITE, ITEM_LUCARIONITE, ITEM_ABOMASITE, ITEM_KANGASKHANITE,
    ITEM_GYARADOSITE, ITEM_ABSOLITE, ITEM_ALAKAZITE, ITEM_HERACRONITE, ITEM_MAWILITE, ITEM_MANECTITE, ITEM_GARCHOMPITE,
    ITEM_LATIASITE, ITEM_LATIOSITE, ITEM_SWAMPERTITE, ITEM_SCEPTILITE, ITEM_SABLENITE, ITEM_ALTARIANITE, ITEM_GALLADITE, ITEM_AUDINITE,
    ITEM_METAGROSSITE, ITEM_SHARPEDONITE, ITEM_SLOWBRONITE, ITEM_STEELIXITE, ITEM_PIDGEOTITE, ITEM_GLALITITE, ITEM_DIANCITE,
    ITEM_CAMERUPTITE, ITEM_LOPUNNITE, ITEM_SALAMENCITE, ITEM_BEEDRILLITE, ITEM_BLUE_ORB, ITEM_RED_ORB, 0xFFFF
};

u16 sMahoganyPreRocketHideout[] = {
    ITEM_TINY_MUSHROOM, ITEM_POKE_BALL, ITEM_POTION, 0xFFFF
};

u16 sMahoganyPostRocketHideout[] = {
    ITEM_SHED_SHELL, ITEM_EJECT_BUTTON, ITEM_AIR_BALLOON, ITEM_IRON_BALL, ITEM_RING_TARGET, ITEM_RED_CARD, ITEM_SNOWBALL, ITEM_WEAKNESS_POLICY,
    ITEM_ADRENALINE_ORB, ITEM_BLUNDER_POLICY, ITEM_EJECT_PACK, ITEM_ROOM_SERVICE, ITEM_THROAT_SPRAY, ITEM_ABILITY_CAPSULE, ITEM_FOCUS_SASH, 0xFFFF
};

BOOL ScrCmd_MartBuy(SCRIPTCONTEXT *ctx) {
    u16 unused UNUSED = ScriptGetVar(ctx);
    
    u16 items[NELEMS(sBadgeMart) + 1];
    u8 badgeCount = 0;
    u8 index = 0;
    u32 i;

    for (i = 0; i < 16; i++) {
        if (PlayerProfile_TestBadgeFlag(Sav2_PlayerData_GetProfileAddr(ctx->fsys->savedata), i) == TRUE) {
            badgeCount++;
        }
    }

    for (i = 0; i < NELEMS(sBadgeMart); i++) {
        if (badgeCount >= sBadgeMart[i].required_badges) {
            items[index] = sBadgeMart[i].item_id;
            index++;
        }
    }

    items[index] = 0xFFFF;
    InitMartUI(ctx->taskman, ctx->fsys, items, 0, 0, 0, 0); // this doesn't honor price overrides
    return TRUE;
}

#endif // MART_EXPANSION

#ifdef POKEATHLON_SHOP_EXPANSION

const struct MartItem sPokeathlonShopSunday[] = {
    { ITEM_RED_APRICORN,   200  },
    { ITEM_BLUE_APRICORN,  200  },
    { ITEM_BLACK_APRICORN, 200  },
    { ITEM_MOOMOO_MILK,    100  },
    { ITEM_GRASS_MAIL,     3000 },
    { ITEM_FLAME_MAIL,    1000 },
    { ITEM_BUBBLE_MAIL,   500  },
    { ITEM_NUGGET,         500  },
    { ITEM_BUBBLE_MAIL,      3000 },
    { ITEM_SPACE_MAIL,     2500 },
    { ITEM_AIR_MAIL,    3000 },
    { ITEM_TUNNEL_MAIL,     3000 },
    { 0xFFFF,              0    },
};

const struct MartItem sPokeathlonShopMonday[] = {
    { ITEM_RED_APRICORN,   200  },
    { ITEM_BLUE_APRICORN,  200  },
    { ITEM_BLACK_APRICORN, 200  },
    { ITEM_MOOMOO_MILK,    100  },
    { ITEM_GRASS_MAIL,     3000 },
    { ITEM_FLAME_MAIL,    1000 },
    { ITEM_BUBBLE_MAIL,   500  },
    { ITEM_NUGGET,         500  },
    { ITEM_BUBBLE_MAIL,      3000 },
    { ITEM_SPACE_MAIL,     2500 },
    { ITEM_AIR_MAIL,    3000 },
    { ITEM_TUNNEL_MAIL,     3000 },
    { 0xFFFF,              0    },
};

const struct MartItem sPokeathlonShopTuesday[] = {
   { ITEM_RED_APRICORN,   200  },
    { ITEM_BLUE_APRICORN,  200  },
    { ITEM_BLACK_APRICORN, 200  },
    { ITEM_MOOMOO_MILK,    100  },
    { ITEM_GRASS_MAIL,     3000 },
    { ITEM_FLAME_MAIL,    1000 },
    { ITEM_BUBBLE_MAIL,   500  },
    { ITEM_NUGGET,         500  },
    { ITEM_BUBBLE_MAIL,      3000 },
    { ITEM_SPACE_MAIL,     2500 },
    { ITEM_AIR_MAIL,    3000 },
    { ITEM_TUNNEL_MAIL,     3000 },
    { 0xFFFF,              0    },
};

const struct MartItem sPokeathlonShopWednesday[] = {
   { ITEM_RED_APRICORN,   200  },
    { ITEM_BLUE_APRICORN,  200  },
    { ITEM_BLACK_APRICORN, 200  },
    { ITEM_MOOMOO_MILK,    100  },
    { ITEM_GRASS_MAIL,     3000 },
    { ITEM_FLAME_MAIL,    1000 },
    { ITEM_BUBBLE_MAIL,   500  },
    { ITEM_NUGGET,         500  },
    { ITEM_BUBBLE_MAIL,      3000 },
    { ITEM_SPACE_MAIL,     2500 },
    { ITEM_AIR_MAIL,    3000 },
    { ITEM_TUNNEL_MAIL,     3000 },
    { 0xFFFF,              0    },
};

const struct MartItem sPokeathlonShopThursday[] = {
   { ITEM_RED_APRICORN,   200  },
    { ITEM_BLUE_APRICORN,  200  },
    { ITEM_BLACK_APRICORN, 200  },
    { ITEM_MOOMOO_MILK,    100  },
    { ITEM_GRASS_MAIL,     3000 },
    { ITEM_FLAME_MAIL,    1000 },
    { ITEM_BUBBLE_MAIL,   500  },
    { ITEM_NUGGET,         500  },
    { ITEM_BUBBLE_MAIL,      3000 },
    { ITEM_SPACE_MAIL,     2500 },
    { ITEM_AIR_MAIL,    3000 },
    { ITEM_TUNNEL_MAIL,     3000 },
    { 0xFFFF,              0    },
};

const struct MartItem sPokeathlonShopFriday[] = {
    { ITEM_RED_APRICORN,   200  },
    { ITEM_BLUE_APRICORN,  200  },
    { ITEM_BLACK_APRICORN, 200  },
    { ITEM_MOOMOO_MILK,    100  },
    { ITEM_GRASS_MAIL,     3000 },
    { ITEM_FLAME_MAIL,    1000 },
    { ITEM_BUBBLE_MAIL,   500  },
    { ITEM_NUGGET,         500  },
    { ITEM_BUBBLE_MAIL,      3000 },
    { ITEM_SPACE_MAIL,     2500 },
    { ITEM_AIR_MAIL,    3000 },
    { ITEM_TUNNEL_MAIL,     3000 },
    { 0xFFFF,              0    },
};

const struct MartItem sPokeathlonShopSaturday[] = {
   { ITEM_RED_APRICORN,   200  },
    { ITEM_BLUE_APRICORN,  200  },
    { ITEM_BLACK_APRICORN, 200  },
    { ITEM_MOOMOO_MILK,    100  },
    { ITEM_GRASS_MAIL,     3000 },
    { ITEM_FLAME_MAIL,    1000 },
    { ITEM_BUBBLE_MAIL,   500  },
    { ITEM_NUGGET,         500  },
    { ITEM_BUBBLE_MAIL,      3000 },
    { ITEM_SPACE_MAIL,     2500 },
    { ITEM_AIR_MAIL,    3000 },
    { ITEM_TUNNEL_MAIL,     3000 },
    { 0xFFFF,              0    },
};

#endif // POKEATHLON_SHOP_EXPANSION
